blank_issues_enabled: false
contact_links:
  - name: WordPress Community Support
    url: https://wordpress.org/support/
    about: For general WordPress support.
  - name: Make WordPress.org Marketing Blog
    url: https://make.wordpress.org/marketing/
    about: Read the latest meeting notes and updates from the team.
  - name: Make WordPress.org Marketing Slack
    url: https://wordpress.slack.com/archives/C0GKJ7TFA
    about: Meet and converse with members of the WordPress Marketing Team.
